# Generated by Django 5.1.7 on 2025-05-13 15:18

import urls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_vode', models.CharField(default=urls.models.generate_short_code, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
