# Generated by Django 5.1.7 on 2025-05-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_vode',
            new_name='short_code',
        ),
    ]
